name: TSCam
version: 1.1.0
main: com.mikemik44.tsgrabber.TSCamShowcase
api-version: '1.20'
depend: [ProtocolLib]

commands:
  tsentity:
    description: Use of editing entity
    usage: /tsentity <cancel/wand/confirm/change>
    permission: tsentity.admin