name: TSEntity
version: 1.2.2
main: com.mikemik44.tsentity.TSEntity
api-version: '1.20'

commands:
  tsentity:
    description: Use of editing entity
    usage: /tsentity <cancel/wand/confirm/change>
    permission: tsentity.admin